services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "carlitos8686"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "C@rl0s86"
      - key: WEBHOOK_URL
        value: "https://n8n.onrender.com"
      - key: N8N_HOST
        value: "n8n.onrender.com"
      - key: N8N_PORT
        value: "5678"
      - key: GENERIC_TIMEZONE
        value: "Europe/Madrid"
